package com.project.noiseTypes;

import com.project.NoiseGenerator;

public abstract class PerlinBase implements NoiseTemplate {

    /**
     * gives the height of a single point generated by perlin noise
     * @param seed the seed
     * @param px the x cord of the pixel (compressed)
     * @param py the y cord of the pixel (compressed)
     * @return the height
     */
    protected double samplePerlin(long seed, double px, double py) {
        //gets the 4 corners on the noisescale surronding this point
        int x0 = (int) Math.floor(px);
        int y0 = (int) Math.floor(py);
        int x1 = x0 + 1;
        int y1 = y0 + 1;

        //same as value, make sure it is continuous and differentiable
        double tx = NoiseGenerator.smoothstep(px - x0);
        double ty = NoiseGenerator.smoothstep(py - y0);

        //gest the dot product between the current point and each of the corners with their own gradient vector
        double dot00 = NoiseGenerator.dotGradient(seed, x0, y0, px, py);
        double dot10 = NoiseGenerator.dotGradient(seed, x1, y0, px, py);
        double dot01 = NoiseGenerator.dotGradient(seed, x0, y1, px, py);
        double dot11 = NoiseGenerator.dotGradient(seed, x1, y1, px, py);

        //same blending process as value noise, first the top and bottom x cords, then the y cord between the two x cords
        return NoiseGenerator.lerp(NoiseGenerator.lerp(dot00, dot10, tx), NoiseGenerator.lerp(dot01, dot11, tx), ty);

    }
}
